name: 🐛 Relay Connect Bug
description: Report a bug or unexpected behavior in Relay Connect
labels: ['need confirmation']

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to Relay Connect! ✊

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure you're using the latest version of Relay Connect.
      options:
        - label: I confirm that I'm using the latest version of Relay Connect
          required: true
        - label: I confirm that I searched for my issue in https://github.com/yamanahlawat/relay-connect/issues before opening this issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: |
        Please provide your environment details:
        - Relay Connect version (or commit hash)
        - Browser and version
        - Operating System
        - Node.js version
      render: Text
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide detailed steps to reproduce the issue:
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Error Messages
      description: |
        Please include any relevant logs, error messages, or screenshots.
      render: shell
